### ISSUE TITLE
ES6 instead of CoffeeScript?

### ISSUE THREAD

**Issue by iam4x** [steelbrain/linter-plus#2]
Since Atom uses babeljs for transpiling ES6 code, it makes more sense to use ES6 classes than CoffeeScript ones.

For instance: https://github.com/iam4x/linter-plus-eslint/blob/master/lib%2Flinter-plus-eslint.js

Won't you mind me to drop a PR with ES6 code?

**Comment by steelbrain** [comment]
I love ES6 code, if you look at my other repositories, I have consumed it heavily, and I feel honoured when you said you want to do a PR. But My friend, let's not hit everything like a nail when we have a hammer in hand.
I have done several rewrites from coffee-script to ES6 in my codebase, most of them were appropriate, but in some cases, like [this one][1] and the current repo, it just increases code complexity.

[1]:https://github.com/steelbrain/Atom-Hack/pull/34

**Comment by iam4x** [comment]
I will send you tons of examples where CoffeeScript fails :)

* https://gist.github.com/Spaceghost/9055820 (scopped vars wtf)
* http://procbits.com/2012/05/18/why-do-all-the-great-node-js-developers-hate-coffeescript
* http://www.quora.com/Why-do-people-hate-CoffeeScript
* http://raganwald.com/2013/07/29/I-hated-hated-hated-this-coffeescript.html

Plain JavaScript makes things a lot clearer, it doesn't a nice shiny looking syntax but with ES6 it became better :)

**Comment by steelbrain** [comment]
I agree it makes things clearer, I agree it looks shiny. and I can send you tons of links which say Coffee-Script is better than ES6. But I won't do that, 'cause I love both of them. I use the right tool for the right job, and for this particular job, coffeescript is the best.
