### ISSUE TITLE
Error doesn't show on gutter when cursor on line

### ISSUE THREAD

**Issue by iam4x** [steelbrain/linter-plus#4]
### Cursor on error line:
![screen shot 2015-05-25 at 17 03 01](https://cloud.githubusercontent.com/assets/893837/7798877/ef691e7c-02ff-11e5-93d5-ab46ae14f889.png)

### Cursor not on error line:
![screen shot 2015-05-25 at 17 03 19](https://cloud.githubusercontent.com/assets/893837/7798880/f81ba0a8-02ff-11e5-93ef-fa22c0de8492.png)

**Comment by steelbrain** [comment]
Can you talk to me in the freenode irc, I am @steelbrain

**Comment by steelbrain** [comment]
Fixed in master.
